version: "3.7"

services:
  postgres:
    image: postgres:13.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sketch
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
