version: "3.7"

services:
  sketch:
    image: rafaelfiume/sketch:latest
    ports:
      - "8080:8080"
    environment:
      - ENV=$ENV
      - DB_URL=$DB_URL
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
    depends_on:
      - database
    healthcheck:
      test: ["CMD-SHELL", "curl sketch:8080/ping"]

  database:
    image: postgres:13.6
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sketch
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
