package org.fiume.sketch.storage.auth0.postgres

import cats.effect.IO
import cats.implicits.*
import doobie.ConnectionIO
import doobie.implicits.*
import doobie.postgres.implicits.*
import munit.ScalaCheckEffectSuite
import org.fiume.sketch.shared.auth0.domain.{AccountState, Passwords, User, UserId}
import org.fiume.sketch.shared.auth0.domain.AccountState.SoftDeleted
import org.fiume.sketch.shared.auth0.domain.Passwords.HashedPassword
import org.fiume.sketch.shared.auth0.domain.User.*
import org.fiume.sketch.shared.auth0.jobs.{JobId, PermanentAccountDeletionJob}
import org.fiume.sketch.shared.auth0.testkit.PasswordsGens.given
import org.fiume.sketch.shared.auth0.testkit.UserGens.given
import org.fiume.sketch.shared.testkit.ClockContext
import org.fiume.sketch.shared.testkit.syntax.OptionSyntax.*
import org.fiume.sketch.storage.auth0.postgres.DatabaseCodecs.given
import org.fiume.sketch.storage.testkit.DockerPostgresSuite
import org.scalacheck.ShrinkLowPriority
import org.scalacheck.effect.PropF.forAllF

import java.time.Instant
import java.time.temporal.ChronoUnit.MILLIS
import scala.concurrent.duration.*

class PostgresUsersStoreSpec
    extends ScalaCheckEffectSuite
    with DockerPostgresSuite
    with ClockContext
    with PostgresUsersStoreSpecContext
    with ShrinkLowPriority:

  override def scalaCheckTestParameters = super.scalaCheckTestParameters.withMinSuccessfulTests(5)

  test("stores credentials"):
    forAllF { (credentials: UserCredentials) =>
      will(cleanStorage) {
        PostgresUsersStore.make[IO](transactor(), makeFrozenClock()).use { store =>
          for
            uuid <- store.store(credentials).ccommit

            result <- store.fetchCredentials(credentials.username).ccommit
//
          yield assertEquals(result.someOrFail, UserCredentials.make(uuid, credentials))
        }
      }
    }

  test("fetches user account".only):
    forAllF { (credentials: UserCredentials) =>
      will(cleanStorage) {
        PostgresUsersStore.make[IO](transactor(), makeFrozenClock()).use { store =>
          for
            uuid <- store.store(credentials).ccommit

            result <- store.fetchAccount(credentials.username).ccommit.map(_.someOrFail)
//
          yield
            assertEquals(result.uuid, uuid)
            assertEquals(result.credentials, credentials)
            result.state match
              case AccountState.Active(_) => assert(true)
              case _                      => fail(s"Expected AccountState.Active, got ${result.state}")
        }
      }
    }

  test("updates user password"):
    forAllF { (credentials: UserCredentials, newPassword: HashedPassword) =>
      will(cleanStorage) {
        PostgresUsersStore.make[IO](transactor(), makeFrozenClock()).use { store =>
          for
            uuid <- store.store(credentials).ccommit

            _ <- store.updatePassword(uuid, newPassword).ccommit

            result <- store.fetchPassword(uuid).ccommit
          yield assertEquals(result, newPassword)
        }
      }
    }

  test("marks account for deletion"):
    forAllF { (fstCreds: UserCredentials, sndCreds: UserCredentials) =>
      will(cleanStorage) {
        val deletedAt = Instant.now()
        val frozenClock = makeFrozenClock(deletedAt)
        val permantDeletionDelay = 1.second
        PostgresUsersStore.make[IO](transactor(), frozenClock).use { store =>
          for
            fstUserId <- store.store(fstCreds).ccommit
            sndUserId <- store.store(sndCreds).ccommit

            _ <- store.markForDeletion(fstUserId, permantDeletionDelay).ccommit

            fstAccount <- store.fetchAccount(fstCreds.username).ccommit.map(_.someOrFail)
            fstAccountDeletionJob <- store.fetchPermanentDeletionJob(fstUserId).ccommit.map(_.someOrFail)
            sndAccount <- store.fetchAccount(sndCreds.username).ccommit.map(_.someOrFail)
            sndAccountDeletionJob <- store.fetchPermanentDeletionJob(sndUserId).ccommit
          yield
            assert(!fstAccount.isActive)
            assertEquals(fstAccount.state, SoftDeleted(deletedAt.truncatedTo(MILLIS)))
            val permanentDeletionAt = deletedAt.plusSeconds(permantDeletionDelay.toSeconds).truncatedTo(MILLIS)
            assertEquals(
              fstAccountDeletionJob,
              PermanentAccountDeletionJob(
                fstAccountDeletionJob.uuid, // ignore checking the job id generated by Postgres
                fstUserId,
                permanentDeletionAt
              )
            )
            assert(sndAccount.isActive)
            assert(sndAccountDeletionJob.isEmpty, clue = "Expected no deletion job for the second account")
        }
      }
    }

  test("timestamps createdAt and updatedAt upon storage"):
    forAllF { (credentials: UserCredentials) =>
      will(cleanStorage) {
        PostgresUsersStore.make[IO](transactor(), makeFrozenClock()).use { store =>
          for
            uuid <- store.store(credentials).ccommit

            createdAt <- store.fetchCreatedAt(uuid).ccommit
            updatedAt <- store.fetchUpdatedAt(uuid).ccommit
//
          yield assertEquals(createdAt, updatedAt)
        }
      }
    }

  test("timestamps updatedAt upon update"):
    forAllF { (credentials: UserCredentials, newPassword: HashedPassword) =>
      will(cleanStorage) {
        PostgresUsersStore.make[IO](transactor(), makeFrozenClock()).use { store =>
          for
            uuid <- store.store(credentials).ccommit

            _ <- store.updatePassword(uuid, newPassword).ccommit

            createdAt <- store.fetchCreatedAt(uuid).ccommit
            updatedAt <- store.fetchUpdatedAt(uuid).ccommit
          yield assert(
            updatedAt.isAfter(createdAt),
            clue = s"updatedAt=${updatedAt} should be after createdAt=${createdAt}"
          )
        }
      }
    }

trait PostgresUsersStoreSpecContext:
  def cleanStorage: ConnectionIO[Unit] =
    sql"TRUNCATE TABLE auth.account_deletion_jobs, auth.users".update.run.void

  extension (store: PostgresUsersStore[IO])
    def fetchPassword(uuid: UserId): ConnectionIO[HashedPassword] =
      sql"SELECT password_hash FROM auth.users WHERE uuid = ${uuid}".query[HashedPassword].unique

    def fetchCreatedAt(uuid: UserId): ConnectionIO[Instant] =
      sql"SELECT created_at FROM auth.users WHERE uuid = ${uuid}".query[Instant].unique

    def fetchUpdatedAt(uuid: UserId): ConnectionIO[Instant] =
      sql"SELECT updated_at FROM auth.users WHERE uuid = ${uuid}".query[Instant].unique

    def fetchPermanentDeletionJob(uuid: UserId): ConnectionIO[Option[PermanentAccountDeletionJob]] =
      sql"SELECT * FROM auth.account_deletion_jobs WHERE user_id = ${uuid}".query[PermanentAccountDeletionJob].option
