addSbtPlugin(Plugin.DependencyGraph)
addSbtPlugin(Plugin.DotEnv)
addSbtPlugin(Plugin.Git)
addSbtPlugin(Plugin.SbtNativePackager)
addSbtPlugin(Plugin.Scalafix)
addSbtPlugin(Plugin.ScalaFmt)
addSbtPlugin(Plugin.Tpolecat)
