version: "3.8"

services:
  visual-sketch:
    image: rafaelfiume/visual-sketch:${VISUAL_SKETCH_IMAGE_TAG}
    ports:
      - "8181:80"
    depends_on:
      - sketch

  sketch:
    image: rafaelfiume/sketch:${SKETCH_IMAGE_TAG}
    container_name: sketch
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
      - "9999:9999" # expose JMX port
    environment:
      - ENV=$ENV
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - HTTP_REQ_RES_LOG_ENABLED=${HTTP_REQ_RES_LOG_ENABLED}
      - HTTP_CORS_ALLOWS_ORIGIN=${HTTP_CORS_ALLOWS_ORIGIN}
      - DOCUMENT_MB_SIZE_LIMIT=${DOCUMENT_MB_SIZE_LIMIT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - JAVA_OPTS=-Xmx2g -XX:+UseG1GC -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  database:
    # Don't forget to update DockerDatabaseConfig
    image: postgres:15.3-bullseye
    container_name: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
