CREATE TABLE documents
(
  id                        INTEGER             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                      VARCHAR                                                              NOT NULL,
  description               VARCHAR,
  updated_at_utc            TIMESTAMPTZ         DEFAULT now()                                    NOT NULL,
  bytes                     BYTEA,

  UNIQUE (name)
)